# Generated by Django 3.0.7 on 2020-06-12 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filecabinet', '0002_auto_20200612_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
