# Generated by Django 3.0.7 on 2020-06-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filecabinet', '0003_auto_20200612_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
    ]
